### PR TITLE
New nodejs module with smarter testing and library functions

### PR DESCRIPTION
**Pull request by jjosef**
I've started re-writing the node module for Balanced as the projects I'm working on require a more versatile and comprehensive solution to working with Balanced from within a node app. Right now it is a work in progress, and is why I have not replaced the lib folder yet.

Please take a look at examples and tests and offer criticisms and ideas to make this become the mainstream module. I will be generating the scenarios soon, and they will be based off the tests code I have already written.

### CODE REVIEW

**Comment by matthewfl** [comment]
so that scenarios folder needs to stay as that is where all the scenarios in the docs come from, you can clean up the way that they are build if you want

https://github.com/balanced/balanced-ruby/tree/master/scenarios
https://github.com/balanced/balanced-php/tree/master/scenarios
https://github.com/balanced/balanced-python/tree/master/scenarios

**Comment by jjosef** [comment]
Thanks for the reference Matthew, I planned on replicating the same structure, just thinking of a simple format with less files involved.

**Comment by jjosef** [comment]
One question, do you still need the Accounts scenarios since they are deprecated?

**Comment by remear** [comment]
Yes. They're deprecated but not removed. Some are still included at the bottom of the API docs.

**Comment by remear** [comment]
@jjosef How's this going?

**Comment by jjosef** [comment]
@remear I haven't had much time lately to contribute, and have been out of town. Will get back to this in the next week or so. Keep up with progress here: https://github.com/uh-sem-blee/balanced-node-new -- already using this in a production site.

**Comment by remear** [comment]
@jjosef We've released a new node client for v1.1 of the API. Feel free to check it out. I'm going to go ahead and close this.

**Pull request closed without merging**
